# Generated by Django 5.0 on 2023-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_collection_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
    ]
